spring:
  datasource:
    url: jdbc:postgresql://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}?serverTimezone=Europe/Bucharest&characterEncoding=UTF-8
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    generate-ddl: true
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    properties.hibernate.jdbc.lob.non_contextual_creation: true
  multipart:
    maxFileSize: 20MB
    maxRequestSize: 30MB
  data:
    web:
      pageable:
        size-parameter: size
        page-parameter: page
        default-page-size: 20
  mvc:
    locale: ro
  mail:
    host: email-smtp.eu-west-1.amazonaws.com
    port: 587 #  25, 465 or 587
    # This is Different from AWS_ACCESS_ID and AWS_SECRET_KEY.  Required to generate AWS SES production credentials: https://docs.aws.amazon.com/ses/latest/DeveloperGuide/smtp-credentials.html
    username: ${AWS_SES_USERNAME}
    password:  ${AWS_SES_PASSWORD}
    properties:
      transport:
        protocol: 'smtp'
      mail:
        smtp:
          auth: true # set the access user/password and change this to true
          starttls:
            enable: true
  cache:
    cache-names: users
app:
  jwtSecret: ORy9HWgKoZPAs50ECKw0
  jwtExpirationInMs: 1728000000   # two days expiration time, can be extended
  email:
    documenturl: ${DOMAIN_URL:https://staging.legiinlucru.ro}/api/documents/ #TODO: change this once the app is deployed and a domain exists
    signupurl: ${DOMAIN_URL:https://staging.legiinlucru.ro}/register
    sender: ${AWS_SES_EMAIL}
storage:
  aws:
    region: ${AWS_REGION}
    access:
      key:
        id: ${AWS_ACCESS_ID}
        secret: ${AWS_SECRET_KEY}
    s3:
      documentBucket: ${AWS_DOCUMENT_BUCKET}
  filesystem:
    directory: legal_consult_uploads
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
