spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://${MYSQL_DB_URL:localhost}:5432/legalconsultation?serverTimezone=Europe/Bucharest&characterEncoding=UTF-8
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    generate-ddl: true
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    properties.hibernate.jdbc.lob.non_contextual_creation: true
  multipart:
    maxFileSize: 20MB
    maxRequestSize: 30MB
  data:
    web:
      pageable:
        size-parameter: size
        page-parameter: page
        default-page-size: 20
  mvc:
    locale: ro
  mail:
    host: '127.0.0.1'
    port: 1025
    username: ""
    password: ""
    properties:
      transport:
        protocol: 'smtp'
      mail:
        smtp:
          auth: false # set the access user/password and change this to true
          starttls:
            enable: true
  cache:
    cache-names: users
app:
  jwtSecret: ORy9HWgKoZPAs50ECKw0
  jwtExpirationInMs: 1728000000   # two days expiration time, can be extended
  signupurl: 'http://localhost:4200/authentication/sign-up'
  email:
    sender: noreply@legalconsultation.ro # temporary value. change this to a real email that is validated in SES : https://docs.aws.amazon.com/ses/latest/DeveloperGuide/verify-email-addresses-procedure.html

storage:
  aws:
    region: us-east-1
    access:
      key:
        id: aws_access_id
        secret: aws_access_secret
    s3:
      documentBucket: documents
  filesystem:
    directory: ~
