name: Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Cache the dependencies
      uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11

    - name: Build with Maven
      run: mvn package

    - name: Build the Docker image
      if: github.ref == 'refs/heads/develop'
      run: |
        docker build . \
        --file etc/docker/Dockerfile-dev \
        --tag ${{ secrets.ORGANIZATION }}/${{ secrets.REPO }}:latest

    - name: Login to docker registry
      if: github.ref == 'refs/heads/develop'
      run: docker login -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }}

    - name: Push to docker registry
      if: github.ref == 'refs/heads/develop'
      run: docker push ${{ secrets.ORGANIZATION }}/${{ secrets.REPO }}:latest
